-- Drop existing policies first
DROP POLICY IF EXISTS "Allow users to view messages for watch parties they are in" ON public.watch_party_messages;
DROP POLICY IF EXISTS "Allow users to insert messages for watch parties they are in" ON public.watch_party_messages;
DROP POLICY IF EXISTS "Allow users to view bets for watch parties they are in" ON public.watch_party_bets;
DROP POLICY IF EXISTS "Allow users to insert their own bets" ON public.watch_party_bets;
DROP POLICY IF EXISTS "Allow users to update their own bets" ON public.watch_party_bets;

-- Drop existing tables if they exist
DROP TABLE IF EXISTS public.watch_party_messages CASCADE;
DROP TABLE IF EXISTS public.watch_party_bets CASCADE;

-- Create watch_party_messages table
CREATE TABLE public.watch_party_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_party_id UUID REFERENCES public.watch_parties(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    username TEXT NOT NULL,
    avatar_url TEXT,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    team_preference TEXT,
    type TEXT DEFAULT 'message',
    bet_amount DECIMAL(10,2),
    bet_choice TEXT,
    odds DECIMAL(10,2),
    result BOOLEAN,
    payout DECIMAL(10,2),
    original_user TEXT,
    is_system_message BOOLEAN DEFAULT FALSE
);

-- Create watch_party_bets table
CREATE TABLE public.watch_party_bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_party_id UUID REFERENCES public.watch_parties(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    choice TEXT NOT NULL,
    odds DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    result BOOLEAN,
    payout DECIMAL(10,2)
);

-- Add RLS policies for watch_party_messages
ALTER TABLE public.watch_party_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view messages for watch parties they are in" ON public.watch_party_messages
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.watch_party_members
            WHERE watch_party_members.watch_party_id = watch_party_messages.watch_party_id
            AND watch_party_members.user_id = auth.uid()
        )
    );

CREATE POLICY "Allow users to insert messages for watch parties they are in" ON public.watch_party_messages
    FOR INSERT
    WITH CHECK (
        (
            EXISTS (
                SELECT 1 FROM public.watch_party_members
                WHERE watch_party_members.watch_party_id = watch_party_messages.watch_party_id
                AND watch_party_members.user_id = auth.uid()
            )
            AND user_id = auth.uid()
        )
        OR is_system_message = true
    );

-- Add RLS policies for watch_party_bets
ALTER TABLE public.watch_party_bets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view bets for watch parties they are in" ON public.watch_party_bets
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.watch_party_members
            WHERE watch_party_members.watch_party_id = watch_party_bets.watch_party_id
            AND watch_party_members.user_id = auth.uid()
        )
    );

CREATE POLICY "Allow users to insert their own bets" ON public.watch_party_bets
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own bets" ON public.watch_party_bets
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS watch_party_messages_watch_party_id_idx ON public.watch_party_messages(watch_party_id);
CREATE INDEX IF NOT EXISTS watch_party_messages_user_id_idx ON public.watch_party_messages(user_id);
CREATE INDEX IF NOT EXISTS watch_party_messages_created_at_idx ON public.watch_party_messages(created_at);

CREATE INDEX IF NOT EXISTS watch_party_bets_watch_party_id_idx ON public.watch_party_bets(watch_party_id);
CREATE INDEX IF NOT EXISTS watch_party_bets_user_id_idx ON public.watch_party_bets(user_id);
CREATE INDEX IF NOT EXISTS watch_party_bets_created_at_idx ON public.watch_party_bets(created_at);
