// NFL Teams Data - All 32 teams with their information and Wikipedia logo URLs
export const NFL_TEAMS = {
  ARI: {
    name: 'Arizona Cardinals',
    city: 'Arizona',
    mascot: 'Cardinals',
    conference: 'NFC',
    division: 'West',
    colors: ['#97233F', '#000000', '#FFB612'],
    logo: '🏈', // Fallback emoji
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg',
  },
  ATL: {
    name: 'Atlanta Falcons',
    city: 'Atlanta',
    mascot: 'Falcons',
    conference: 'NFC',
    division: 'South',
    colors: ['#A71930', '#000000', '#A5ACAF'],
    logo: '🦅',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg',
  },
  BAL: {
    name: 'Baltimore Ravens',
    city: 'Baltimore',
    mascot: 'Ravens',
    conference: 'AFC',
    division: 'North',
    colors: ['#241773', '#000000', '#9E7C0C'],
    logo: '🐦',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg',
  },
  BUF: {
    name: 'Buffalo Bills',
    city: 'Buffalo',
    mascot: 'Bills',
    conference: 'AFC',
    division: 'East',
    colors: ['#00338D', '#C60C30'],
    logo: '🦬',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg',
  },
  CAR: {
    name: 'Carolina Panthers',
    city: 'Carolina',
    mascot: 'Panthers',
    conference: 'NFC',
    division: 'South',
    colors: ['#0085CA', '#101820', '#BFC0BF'],
    logo: '🐾',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg',
  },
  CHI: {
    name: 'Chicago Bears',
    city: 'Chicago',
    mascot: 'Bears',
    conference: 'NFC',
    division: 'North',
    colors: ['#0B162A', '#C83803'],
    logo: '🐻',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg',
  },
  CIN: {
    name: 'Cincinnati Bengals',
    city: 'Cincinnati',
    mascot: 'Bengals',
    conference: 'AFC',
    division: 'North',
    colors: ['#FB4F14', '#000000'],
    logo: '🐅',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg',
  },
  CLE: {
    name: 'Cleveland Browns',
    city: 'Cleveland',
    mascot: 'Browns',
    conference: 'AFC',
    division: 'North',
    colors: ['#311D00', '#FF3C00'],
    logo: '🟤',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg',
  },
  DAL: {
    name: 'Dallas Cowboys',
    city: 'Dallas',
    mascot: 'Cowboys',
    conference: 'NFC',
    division: 'East',
    colors: ['#003594', '#869397', '#FFFFFF'],
    logo: '⭐',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg',
  },
  DEN: {
    name: 'Denver Broncos',
    city: 'Denver',
    mascot: 'Broncos',
    conference: 'AFC',
    division: 'West',
    colors: ['#FB4F14', '#002244'],
    logo: '🐴',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg',
  },
  DET: {
    name: 'Detroit Lions',
    city: 'Detroit',
    mascot: 'Lions',
    conference: 'NFC',
    division: 'North',
    colors: ['#0076B6', '#B0B7BC', '#000000'],
    logo: '🦁',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg',
  },
  GB: {
    name: 'Green Bay Packers',
    city: 'Green Bay',
    mascot: 'Packers',
    conference: 'NFC',
    division: 'North',
    colors: ['#203731', '#FFB612'],
    logo: '🧀',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg',
  },
  HOU: {
    name: 'Houston Texans',
    city: 'Houston',
    mascot: 'Texans',
    conference: 'AFC',
    division: 'South',
    colors: ['#03202F', '#A71930'],
    logo: '🤠',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg',
  },
  IND: {
    name: 'Indianapolis Colts',
    city: 'Indianapolis',
    mascot: 'Colts',
    conference: 'AFC',
    division: 'South',
    colors: ['#002C5F', '#A2AAAD'],
    logo: '🐎',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg',
  },
  JAX: {
    name: 'Jacksonville Jaguars',
    city: 'Jacksonville',
    mascot: 'Jaguars',
    conference: 'AFC',
    division: 'South',
    colors: ['#101820', '#D7A22A', '#9F792C'],
    logo: '🐆',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg',
  },
  KC: {
    name: 'Kansas City Chiefs',
    city: 'Kansas City',
    mascot: 'Chiefs',
    conference: 'AFC',
    division: 'West',
    colors: ['#E31837', '#FFB81C'],
    logo: '🔥',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg',
  },
  LV: {
    name: 'Las Vegas Raiders',
    city: 'Las Vegas',
    mascot: 'Raiders',
    conference: 'AFC',
    division: 'West',
    colors: ['#000000', '#A5ACAF'],
    logo: '⚔️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ec/Las_Vegas_Raiders_logo.svg',
  },
  LAC: {
    name: 'Los Angeles Chargers',
    city: 'Los Angeles',
    mascot: 'Chargers',
    conference: 'AFC',
    division: 'West',
    colors: ['#0080C6', '#FFC20E', '#FFFFFF'],
    logo: '⚡',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/72/Los_Angeles_Chargers_logo.svg',
  },
  LAR: {
    name: 'Los Angeles Rams',
    city: 'Los Angeles',
    mascot: 'Rams',
    conference: 'NFC',
    division: 'West',
    colors: ['#003594', '#FFA300', '#FF8200'],
    logo: '🐏',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg',
  },
  MIA: {
    name: 'Miami Dolphins',
    city: 'Miami',
    mascot: 'Dolphins',
    conference: 'AFC',
    division: 'East',
    colors: ['#008E97', '#FC4C02', '#005778'],
    logo: '🐬',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg',
  },
  MIN: {
    name: 'Minnesota Vikings',
    city: 'Minnesota',
    mascot: 'Vikings',
    conference: 'NFC',
    division: 'North',
    colors: ['#4F2683', '#FFC62F'],
    logo: '⚔️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg',
  },
  NE: {
    name: 'New England Patriots',
    city: 'New England',
    mascot: 'Patriots',
    conference: 'AFC',
    division: 'East',
    colors: ['#002244', '#C60C30', '#B0B7BC'],
    logo: '🇺🇸',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg',
  },
  NO: {
    name: 'New Orleans Saints',
    city: 'New Orleans',
    mascot: 'Saints',
    conference: 'NFC',
    division: 'South',
    colors: ['#101820', '#D3BC8D'],
    logo: '⚜️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg',
  },
  NYG: {
    name: 'New York Giants',
    city: 'New York',
    mascot: 'Giants',
    conference: 'NFC',
    division: 'East',
    colors: ['#0B2265', '#A71930', '#A5ACAF'],
    logo: '🗽',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg',
  },
  NYJ: {
    name: 'New York Jets',
    city: 'New York',
    mascot: 'Jets',
    conference: 'AFC',
    division: 'East',
    colors: ['#125740', '#000000', '#FFFFFF'],
    logo: '✈️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg',
  },
  PHI: {
    name: 'Philadelphia Eagles',
    city: 'Philadelphia',
    mascot: 'Eagles',
    conference: 'NFC',
    division: 'East',
    colors: ['#004C54', '#A5ACAF', '#ACC0C6'],
    logo: '🦅',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg',
  },
  PIT: {
    name: 'Pittsburgh Steelers',
    city: 'Pittsburgh',
    mascot: 'Steelers',
    conference: 'AFC',
    division: 'North',
    colors: ['#FFB612', '#101820'],
    logo: '🔩',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg',
  },
  SF: {
    name: 'San Francisco 49ers',
    city: 'San Francisco',
    mascot: '49ers',
    conference: 'NFC',
    division: 'West',
    colors: ['#AA0000', '#B3995D'],
    logo: '🏔️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg',
  },
  SEA: {
    name: 'Seattle Seahawks',
    city: 'Seattle',
    mascot: 'Seahawks',
    conference: 'NFC',
    division: 'West',
    colors: ['#002244', '#69BE28', '#A5ACAF'],
    logo: '🦅',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg',
  },
  TB: {
    name: 'Tampa Bay Buccaneers',
    city: 'Tampa Bay',
    mascot: 'Buccaneers',
    conference: 'NFC',
    division: 'South',
    colors: ['#D50A0A', '#FF7900', '#0A0A08'],
    logo: '🏴‍☠️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg',
  },
  TEN: {
    name: 'Tennessee Titans',
    city: 'Tennessee',
    mascot: 'Titans',
    conference: 'AFC',
    division: 'South',
    colors: ['#0C2340', '#4B92DB', '#C8102E'],
    logo: '⚡',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg',
  },
  WAS: {
    name: 'Washington Commanders',
    city: 'Washington',
    mascot: 'Commanders',
    conference: 'NFC',
    division: 'East',
    colors: ['#5A1414', '#FFB612'],
    logo: '🎖️',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d5/Washington_Commanders_logo.svg',
  },
};

// Helper functions
export const getTeamsList = () => {
  return Object.entries(NFL_TEAMS).map(([abbr, team]) => ({
    abbreviation: abbr,
    ...team,
  }));
};

export const getTeamByAbbreviation = (abbr) => {
  return NFL_TEAMS[abbr] || null;
};

export const getTeamLogo = (abbr) => {
  const team = NFL_TEAMS[abbr];
  return team ? team.logo : '🏈';
};

// Static imports for team logos
const TEAM_LOGOS = {
  ARI: require('./logos/cardinals.png'),
  ATL: require('./logos/falcons.png'),
  BAL: require('./logos/ravens.png'),
  BUF: require('./logos/bills.png'),
  CAR: require('./logos/panthers.png'),
  CHI: require('./logos/bears.png'),
  CIN: require('./logos/bengals.png'),
  CLE: require('./logos/browns.png'),
  DAL: require('./logos/cowboys.png'),
  DEN: require('./logos/broncos.png'),
  DET: require('./logos/lions.png'),
  GB: require('./logos/packers.png'),
  HOU: require('./logos/texans.png'),
  IND: require('./logos/colts.png'),
  JAX: require('./logos/jaguars.png'),
  KC: require('./logos/chiefs.png'),
  LV: require('./logos/raiders.png'),
  LAC: require('./logos/chargers.png'),
  LAR: require('./logos/rams.png'),
  MIA: require('./logos/dolphins.png'),
  MIN: require('./logos/vikings.png'),
  NE: require('./logos/patriots.png'),
  NO: require('./logos/saints.png'),
  NYG: require('./logos/giants.png'),
  NYJ: require('./logos/jets.png'),
  PHI: require('./logos/eagles.png'),
  PIT: require('./logos/steelers.png'),
  SF: require('./logos/49ers.png'),
  SEA: require('./logos/seahawks.png'),
  TB: require('./logos/buccaneers.png'),
  TEN: require('./logos/titans.png'),
  WAS: require('./logos/redskins.png'),
};

export const getTeamLogoUrl = (abbr) => {
  const team = NFL_TEAMS[abbr];
  return team ? TEAM_LOGOS[abbr] : null;
};

export const getTeamName = (abbr) => {
  const team = NFL_TEAMS[abbr];
  return team ? team.name : 'No Team Selected';
};

// Sorted teams for display in settings
export const getSortedTeams = () => {
  return getTeamsList().sort((a, b) => a.name.localeCompare(b.name));
};
